# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules"]
lang: zh # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
title: 简约不简单
description: "编程改变世界"
keywords: 'jekyll,theme,igouc,blog'
author:
  name: gc
  email: gouchao2008@qq.com
  social_links:
    - name: github
      url: https://github.com/SUT-GC/SUT-GC.github.io

user_info:
  github_url: https://github.com/SUT-GC/SUT-GC.github.io
  email_url: gouchao2008@qq.com

home:
  section1: <h1>简约不简单</h1>
  section2: <h2>编程改变世界</h2>
  section3: interest is the source, persistence is the key

blog:
  footer_content: 编程改变世界
paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
  about: /blog/about/
  ppt: /files/powerpoint/
  image: /files/images